//
//  OpenWeatherMap$.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol WeatherProviderImp_OpenWeatherMap$$ : WeatherProviderImp$$ {}

enum WeatherProviderImp_OpenWeatherMap$ : WeatherProviderImp_OpenWeatherMap$$ {}
