//
//  Networking.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 04/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

protocol OpenWeatherMap_Networking : OpenWeatherMap$$ {

    func queryWeather(for locationPredicate: LocationPredicate, completion: @escaping (WeatherQueryResult) -> Void)
}

extension OpenWeatherMap$$ /* *** AUTOGENERATED *** */ {
    typealias Networking = OpenWeatherMap_Networking
}
