disabled_rules:
  - trailing_whitespace
  - unused_closure_parameter
  - colon
  - force_cast
  - force_try
  - identifier_name
  - nesting
  - type_name
  - empty_parentheses_with_trailing_closure
excluded:
  - Pods
  - vendor
line_length: 300
identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - keyPathsForValues
file_length: 500
