//
//  NetworkingImp$.swift
//  WeatherApp/OpenWeatherMap/NetworkingImp
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol OpenWeatherMap_NetworkingImp$$ : OpenWeatherMap$$ {}

enum OpenWeatherMap_NetworkingImp$ : OpenWeatherMap_NetworkingImp$$ {}
