workspace 'WeatherApp.xcworkspace'

platform :ios, '11.3'

use_frameworks!

def shared_non_test_pods
  pod 'Result'
  pod 'Moya', '~> 11.0.2'
  pod 'Swinject', '~> 2.4.0'
  pod 'Then', '~> 2.3.0'
  pod 'SwiftLint', '~> 0.25.1'
  pod 'GZIP', '~> 1.2.1'
  pod 'RxSwift', '~> 4.2.0'
end

def app_pods
  pod 'SwinjectStoryboard', '~> 2.0.1'  
  pod 'RxDataSources', '~> 3.0.2'
  pod 'RxCocoa', '~> 4.2.0'
  pod 'RxCoreData', '~> 0.5.0'
end

def all_test_pods
  pod 'Quick', '~> 1.3.0'
  pod 'Nimble', '~> 7.1.1'
  pod 'Then', '~> 2.3.0'
end

target 'WeatherApp' do
  project 'Modules/WeatherApp/WeatherApp.xcodeproj'
  
  app_pods
  shared_non_test_pods

  target 'WeatherAppTests' do
    inherit! :search_paths
    
    all_test_pods
  end

  target 'WeatherAppUITests' do
    inherit! :search_paths
  end
end

target 'WeatherAppKit' do
  project 'Modules/WeatherAppKit/WeatherAppKit.xcodeproj'
  
  app_pods
  shared_non_test_pods

  target 'WeatherAppKitTests' do
    inherit! :search_paths
    
    all_test_pods
  end
end

target 'OpenWeatherMapKit' do
  project 'Modules/OpenWeatherMapKit/OpenWeatherMapKit.xcodeproj'

  shared_non_test_pods
  
  target 'OpenWeatherMapKitTests' do
    inherit! :search_paths
    
    all_test_pods
  end
end

target 'GenerateOpenWeatherMapPersistentCityInfos' do
  project 'Modules/OpenWeatherMapKit/OpenWeatherMapKit.xcodeproj'

  shared_non_test_pods
end

post_install do |installer|
  # Patch RxSwift for RepeatWhen
  installer.pods_project.targets.each do |target|
    if target.name =~ /^RxSwift/
      puts("Adding RepeatWhen to RxSwift")
      group = target.project.main_group.find_subpath("Pods/RxSwift", true)
      file_ref = group.new_reference("../../Pods-Extras/RxSwift/RepeatWhen.swift")
      target.add_file_references([file_ref])
    end
  end

  # Assume that the set of (pod) sources for macOS is the same as for iOS.
  # Adjust the umbrella/precompiled headers generated by pod tool to remove references to UIKit.
  system("find Pods \\( -name '*-prefix.pch' -o -name '*-umbrella.h' \\) -exec sh -c \"sed 's/UIKit\\/UIKit.h/Foundation\\/Foundation.h/g' '{}' > '{}'.tmp && mv '{}'.tmp '{}'\" \\;")

  # Enforce support for macOS for every target in Pods.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|

      configuration.build_settings['CONFIGURATION_BUILD_DIR'] = '${PODS_CONFIGURATION_BUILD_DIR}'

      # Make macOS a valid configuration.
      configuration.build_settings['SUPPORTED_PLATFORMS'] = 'iphoneos iphonesimulator macosx'
      configuration.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'

      # Remove custom SDKROOT so that it matches the one selected for the build (either iOS or macOS).
      configuration.build_settings.delete('SDKROOT')

      xcconfig_path = configuration.base_configuration_reference.real_path
      xcconfig = Xcodeproj::Config.new(xcconfig_path).to_hash

      #
      frameworkSearchPaths = xcconfig['FRAMEWORK_SEARCH_PATHS']
      if frameworkSearchPaths == "XXX" && xcconfig_path.basename.to_s =~ /(debug|release).xcconfig$/
        puts(frameworkSearchPaths)
        macosFrameworkSearchPaths = frameworkSearchPaths.gsub(/"(\$\{PODS_CONFIGURATION_BUILD_DIR\}\/[.a-zA-Z0-9_-]+)-iOS"( |$)/, '"\1-macOS"\2')

        xcconfig['FRAMEWORK_SEARCH_PATHS'] = ''
        xcconfig['FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]'] = frameworkSearchPaths
        xcconfig['FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]'] = frameworkSearchPaths
        xcconfig['FRAMEWORK_SEARCH_PATHS[sdk=macosx*]'] = macosFrameworkSearchPaths
      end

      #
      # Remove framework search paths not existing when building (dynamic) frameworks
      #
      frameworkSearchPaths = xcconfig['FRAMEWORK_SEARCH_PATHS']
      if frameworkSearchPaths != nil
        frameworkSearchPaths = frameworkSearchPaths.gsub(/"\$\{PODS_CONFIGURATION_BUILD_DIR\}\/[.a-zA-Z0-9_-]+"( |$)/, '')
        xcconfig['FRAMEWORK_SEARCH_PATHS'] = frameworkSearchPaths
      end


      File.open(xcconfig_path, "w") { |file|
        xcconfig.each do |key,value|
          file.puts "#{key} = #{value}"
        end
      }
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      #configuration.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      #configuration.build_settings['SWIFT_EXEC'] = '$(SRCROOT)/../Tools/SWIFT_EXEC-no-coverage'
    end
  end
  # Enforce optimization for Xcode 10 beta.
  installer.pods_project.targets.each do |target|
    if target.name =~ /^RxCoreData$/
      puts("Enforcing Swift optimization for RxCoreData/Xcode 10 beta")
      target.build_configurations.each do |configuration|
        configuration.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      end
    end
  end
end
