//
//  OpenWeatherMap$.swift
//  WeatherApp/CityProviderImp/OpenWeatherMap
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol CityProviderImp_OpenWeatherMap$$ : WeatherProviderImp$$ {}

enum CityProviderImp_OpenWeatherMap$ : CityProviderImp_OpenWeatherMap$$ {}
