//
//  CityProviderImp$.swift
//  WeatherApp/CityProviderImp
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol CityProviderImp$$ {}

public enum CityProviderImp$ : CityProviderImp$$ {}
