//
//  CoreData$$.swift
//  OpenWeatherMapKit/CityQueryingImp/CoreData
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol CityQueryingImp_CoreData$$ : CityQueryingImp$$ {}

enum CityQueryingImp_CoreData$ : CityQueryingImp_CoreData$$ {}
