//
//  LocationPredicate.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 04/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

extension OpenWeatherMap$ {
    
    enum LocationPredicate : Equatable {
        
        case cityName(String)
        case cityId(Int)
        case coordinate(Coordinate)
        case zipCode(String, countryCode: String)
        
        struct Coordinate : Codable, Equatable {
            
            let lat: Double
            let lon: Double
        }
    }
}

extension OpenWeatherMap$$ /* *** AUTOGENERATED *** */ {
    typealias LocationPredicate = OpenWeatherMap$.LocationPredicate
}
