//
//  NetworkingError.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 06/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

import Foundation.NSURLResponse

extension OpenWeatherMap$ {
    
    enum NetworkingError : Swift.Error {
        case httpStatus(statusCode: Int, response: URLResponse?)
        case other(Error)
    }
}

extension OpenWeatherMap$$ /* *** AUTOGENERATED *** */ {
    typealias NetworkingError = OpenWeatherMap$.NetworkingError
}
