//
//  WeatherResponse.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 04/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

extension OpenWeatherMap$ {
    
    struct WeatherResponse : Decodable, Equatable {
        let main: Main
        
        struct Main : Decodable, Equatable {
            let temp: Double
        }
    }
}

extension OpenWeatherMap$$ /* *** AUTOGENERATED *** */ {
    typealias WeatherResponse = OpenWeatherMap$.WeatherResponse
}
