//
//  WeatherQueryResult.swift
//  WeatherApp/OpenWeatherMap
//
//  Created by Grigory Entin on 06/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

import Result

extension OpenWeatherMap$ {
    
    typealias WeatherQueryResult = Result<WeatherResponse, NetworkingError>
}

extension OpenWeatherMap$$ /* *** AUTOGENERATED *** */ {
    typealias WeatherQueryResult = OpenWeatherMap$.WeatherQueryResult
}
