//
//  NetworkingImpContainer.swift
//  OpenWeatherMapKit/NetworkingImp
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

import Swinject
import Then

extension Container : Then {}

extension NetworkingImp_Moya$ {
    
    static var container = Container().then {
        $0.register(Networking.self) { _ in
            MoyaNetworking()
        }
    }
}

extension NetworkingImp$$  /* *** AUTOGENERATED *** */ {
    var container: Container {
        return NetworkingImp_Moya$.container
    }
}
