//
//  NetworkingImp$.swift
//  OpenWeatherMapKit/NetworkingImp
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol NetworkingImp$$ {}

public enum NetworkingImp$ : NetworkingImp$$ {}
