//
//  WeatherProviderImp$.swift
//  WeatherApp/WeatherProviderImp
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol WeatherProviderImp$$ {}

public enum WeatherProviderImp$ : WeatherProviderImp$$ {}
