#! /bin/sh -xe

wd=$(dirname "$0")
srcroot="${wd:?}/.."

projectName="${1:?}"

for suffix in ""
do
	AppIcon="AppIcon${suffix}"
	svg="${wd:?}/${AppIcon:?}.svg"
	xcassets="${srcroot:?}"/"${projectName:?}"/Assets.xcassets
	AppIconSet="${xcassets:?}"/"${AppIcon:?}".appiconset
	mkdir -p "${AppIconSet:?}"
	for i in 20 29 40 58 60 76 80 87 120 152 167 180 1024
	do
		svg2png -w $i "${svg:?}" > "${AppIconSet:?}"/"${AppIcon:?}"-${i}x${i}.png
	done
	cp "${wd:?}"/AppIcon-Contents.json "${AppIconSet:?}"/Contents.json
	if [ z"${suffix}" != "z" ]
	then
		for j in 60 120 180
		do
			svg2png -w 60 "${svg:?}" > "${projectName:?}"/"${projectName:?}"/AlternateAppIcons/"${AppIcon:?}".png
			svg2png -w 120 "${svg:?}" > "${projectName:?}"/"${projectName:?}"/AlternateAppIcons/"${AppIcon:?}"@2x.png
			svg2png -w 180 "${svg:?}" > "${projectName:?}"/"${projectName:?}"/AlternateAppIcons/"${AppIcon:?}"@3x.png
		done
		sed "s/AppIcon-/AppIcon${suffix}-/g" < "${xcassets:?}"/AppIcon.appiconset/Contents.json > "${AppIconSet:?}"/Contents.json
	else
		svg2png -w 1024 "${svg:?}" > "${AppIcon:?}"-1024x1024.png
	fi
done
