//
//  MoyaNetworking.swift
//  OpenWeatherMapKit/NetworkingImp/Moya
//
//  Created by Grigory Entin on 04/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

import Moya

extension NetworkingImp_Moya$ {
    
    struct MoyaNetworking : Networking {
        
        typealias MoyaProvider = Moya.MoyaProvider<MoyaTarget>
        
        let moyaProvider: MoyaProvider
        
        static func defaultMoyaProvider() -> MoyaProvider {
            let plugins: [Moya.PluginType] = [
                APIKeyPlugin(apiKey: "529ff8bbf7587aa9d7038c970c075736"),
                NetworkLoggerPlugin(verbose: true, cURL: true)
            ]
            return MoyaProvider(plugins: plugins)
        }
        
        init(moyaProvider: MoyaProvider = defaultMoyaProvider()) {
            self.moyaProvider = moyaProvider
        }
        
        private func proceedWithRequestWeatherResponse(_ response: Moya.Response) throws -> WeatherResponse {
            let response = try response.filter(statusCode: 200)
            return try response.map(WeatherResponse.self)
        }
        
        func queryWeather(for locationPredicate: LocationPredicate, completion: @escaping (NetworkingWeatherQueryResult) -> Void) {
            moyaProvider.request(.weather(for: locationPredicate)) { (moyaResult) in
                switch moyaResult {
                case .failure(let error):
                    completion(.failure(.other(error)))
                    return
                case .success(let response):
                    let result = NetworkingWeatherQueryResult() {
                        return try self.proceedWithRequestWeatherResponse(response)
                    }
                    completion(result)
                }
            }
        }
    }
}

extension NetworkingImp_Moya$$ /* *** AUTOGENERATED *** */ {
    typealias MoyaNetworking = NetworkingImp_Moya$.MoyaNetworking
}
