//
//  Moya$.swift
//  OpenWeatherMapKit/NetworkingImp/Moya
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol NetworkingImp_Moya$$ : NetworkingImp$$ {}

enum NetworkingImp_Moya$ : NetworkingImp_Moya$$ {}
