//
//  Moya$.swift
//  WeatherApp/OpenWeatherMap/NetworkingImp/Moya
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol OpenWeatherMap_NetworkingImp_Moya$$ : OpenWeatherMap_NetworkingImp$$ {}

enum OpenWeatherMap_NetworkingImp_Moya$ : OpenWeatherMap_NetworkingImp_Moya$$ {}
