#! /usr/bin/perl -w

use strict;
use Getopt::Long qw(:config pass_through);

# Filter out coverage specific options from @ARGV.
my $profile_coverage_mapping;
GetOptions("profile-coverage-mapping" => \$profile_coverage_mapping);

# Proceed with swiftc.
exec(
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc",
    @ARGV);
