//
//  CityListJson$.swift
//  OpenWeatherMapKit/CityQueryingImp/CityListJson
//
//  Created by Grigory Entin on 05/05/2018.
//  Copyright © 2018 Grigory Entin. All rights reserved.
//

//
//  *** AUTOGENERATED - DON'T MODIFY ***
//

protocol CityQueryingImp_CityListJson$$ : CityQueryingImp$$ {}

enum CityQueryingImp_CityListJson$ : CityQueryingImp_CityListJson$$ {}
